### ISSUE TITLE
Make raw json available for non logged in users

### ISSUE THREAD

**Issue by numeroteca** [montera34/pageonex#228]
Currently you can only download the raw json (2c2a7f12) if you are logged in. As reported by @martgnz.

I think the fix might be related to https://github.com/montera34/pageonex/blob/master/app/controllers/threads_controller.rb#L5
```
# this filter is used to prevent an unregistered user form using the app, except if it was just exploring the threads
before_filter :authenticate_user!, :except => ["index", "by_username", "search_by_category", "search", "export"]
```
that should include "raw" among its exceptions.

Is this correct, @xuanxu?

**Comment by xuanxu** [comment]
@numeroteca correct! [PR issued](#229)!
