### ISSUE TITLE
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)

### ISSUE THREAD

**Issue by NoahAssam** [montera34/pageonex#240]
i downloaded docker, made a clone of pageonex, created a container. i am running through windows. following the steps of [You can run pageonex locally using docker-compose and our generated images](https://github.com/montera34/pageonex/blob/master/doc/docker/running-pageonex-locally-with-docker-compose.md).
I'm trying to run pageonex locally 

```

[+] Running 2/2Desktop\pageonexstuuf\pageonex-master>docker-compose up
 - Container pageonex-master-mysql-1  Created                                                                      0.3s
 - Container pageonex-master-app-1    Created                                                                      0.1s
Attaching to pageonex-master-app-1, pageonex-master-mysql-1
pageonex-master-mysql-1  | Warning: World-writable config file '/etc/mysql/conf.d/pageonex.cnf' is ignored
pageonex-master-mysql-1  | 2022-03-08 17:26:53 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
pageonex-master-mysql-1  | 2022-03-08 17:26:53 0 [Note] mysqld (mysqld 5.6.40) starting as process 1 ...
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] Plugin 'FEDERATED' is disabled.
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: The InnoDB memory heap is disabled
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Memory barrier is not used
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Compressed tables use zlib 1.2.3
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Using Linux native AIO
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Using CPU crc32 instructions
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Completed initialization of buffer pool
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Highest supported file format is Barracuda.
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: 128 rollback segment(s) are active.
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Waiting for purge to start
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: 5.6.40 started; log sequence number 1626007
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] Server hostname (bind-address): '*'; port: 3306
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] IPv6 is available.
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note]   - '::' resolves to '::';
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] Server socket created on IP: '::'.
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Warning] 'proxies_priv' entry '@ root@8d2195861cd8' ignored in --skip-name-resolve mode.
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] Event Scheduler: Loaded 0 events
pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] mysqld: ready for connections.
pageonex-master-mysql-1  | Version: '5.6.40'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
pageonex-master-app-1    | ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)
pageonex-master-app-1    | Mysql is unavailable - sleeping
pageonex-master-app-1    | ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)
```

**Comment by rporres** [comment]
Most likely the error is in

```
pageonex-master-mysql-1 | Warning: World-writable config file '/etc/mysql/conf.d/pageonex.cnf' is ignored
```

Mysql is starting in the default port `3306` and we expect to be in the `13306` [here](https://github.com/montera34/pageonex/blob/master/docker-compose.yml#L29)

**Comment by NoahAssam** [comment]
> i downloaded docker, made a clone of pageonex, created a container. i am running through windows. following the steps of [You can run pageonex locally using docker-compose and our generated images](https://github.com/montera34/pageonex/blob/master/doc/docker/running-pageonex-locally-with-docker-compose.md). I'm trying to run pageonex locally
> 
> ```
> 
> [+] Running 2/2Desktop\pageonexstuuf\pageonex-master>docker-compose up
>  - Container pageonex-master-mysql-1  Created                                                                      0.3s
>  - Container pageonex-master-app-1    Created                                                                      0.1s
> Attaching to pageonex-master-app-1, pageonex-master-mysql-1
> pageonex-master-mysql-1  | Warning: World-writable config file '/etc/mysql/conf.d/pageonex.cnf' is ignored
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 0 [Note] mysqld (mysqld 5.6.40) starting as process 1 ...
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] Plugin 'FEDERATED' is disabled.
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: The InnoDB memory heap is disabled
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Memory barrier is not used
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Compressed tables use zlib 1.2.3
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Using Linux native AIO
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Using CPU crc32 instructions
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Completed initialization of buffer pool
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Highest supported file format is Barracuda.
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: 128 rollback segment(s) are active.
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: Waiting for purge to start
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] InnoDB: 5.6.40 started; log sequence number 1626007
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] Server hostname (bind-address): '*'; port: 3306
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] IPv6 is available.
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note]   - '::' resolves to '::';
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] Server socket created on IP: '::'.
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Warning] 'proxies_priv' entry '@ root@8d2195861cd8' ignored in --skip-name-resolve mode.
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] Event Scheduler: Loaded 0 events
> pageonex-master-mysql-1  | 2022-03-08 17:26:53 1 [Note] mysqld: ready for connections.
> pageonex-master-mysql-1  | Version: '5.6.40'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
> pageonex-master-app-1    | ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)
> pageonex-master-app-1    | Mysql is unavailable - sleeping
> pageonex-master-app-1    | ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)
> ```

I'm trying to change the port location of the Mysql from 3306 to 13306. i tried changing the location by opening the mysql and changing the location from within. id get an error when clicking on the file. i then started over completely and made a new clone using  https://github.com/montera34/pageonex.git. now I'm not sure where to find the mysql. overall, I'm not sure how to change the port of the mysql from 3306 to 13306. I'm trying to change the location to solve the earlier problem of not being able to connect to the mysql server.

**Comment by rporres** [comment]
you don't need to change anything, the docker compose file already does it for you.

Can you post the logs of the `docker-compose up` when you use the last version of the repository?

**Comment by numeroteca** [comment]
I've run `docker-compose up` in my Linux OS (Ubuntu 20.04) and I see a different outcome from this lines, where you see that the app is working and the Mysql activated:

```
mysql_1  | 2022-03-29 11:26:36 1 [Note] InnoDB: Completed initialization of buffer pool
app_1    | 1
app_1    | 1
mysql_1  | 2022-03-29 11:26:36 1 [Note] InnoDB: Highest supported file format is Barracuda.
app_1    | Mysql is up - executing command
mysql_1  | 2022-03-29 11:26:36 1 [Note] InnoDB: 128 rollback segment(s) are active.
```
Then later, when Mysql is called it uses port 13306 and it can ran the migration `Invoke db:migrate `:
```
mysql_1  | Version: '5.6.40'  socket: '/var/run/mysqld/mysqld.sock'  port: 13306  MySQL Community Server (GPL)
app_1    | ** Invoke db:migrate (first_time)
app_1    | ** Invoke environment (first_time)
app_1    | ** Execute environment
```
In my case it connects to port 13306, but in yours it does it to 3306. Could you check that your [docker-compose.yml](https://github.com/montera34/pageonex/blob/master/docker-compose.yml#L13) file points to `13306:13306` (line 13)?

What could be the cause of your app not starting earlier? @rporres ideas?

**Comment by NoahAssam** [comment]
the issue has been solved, was missing a file from the pageonex zip file
